import { NextRequest, NextResponse } from 'next/server';
import { datalakeThumbnailService } from '@/lib/datalake-thumbnails';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ fileId: string }> }
) {
  try {
    const { fileId } = await params;
    const { searchParams } = new URL(request.url);
    const size = (searchParams.get('size') || 'medium') as 'small' | 'medium' | 'large';
    
    console.log('🖼️ Thumbnail request for fileId:', fileId, 'size:', size);

    // Validate fileId
    if (!fileId) {
      return NextResponse.json(
        { error: 'File ID is required' },
        { status: 400 }
      );
    }

    // Get thumbnail from Silver layer (thumbnails are pre-generated by process-thumbnails.mjs)
    const thumbnailUrl = await datalakeThumbnailService.getThumbnailUrl(fileId, size);
    
    if (thumbnailUrl) {
      console.log('✅ Thumbnail found in Silver layer, redirecting to:', thumbnailUrl);
      return NextResponse.redirect(thumbnailUrl, {
        headers: {
          'Cache-Control': 'public, max-age=604800, immutable', // Cache for 7 days
        },
      });
    }

    // Thumbnail not found - return placeholder
    // Note: Run scripts/process-thumbnails.mjs to generate thumbnails
    console.log('📭 Thumbnail not found in Silver layer, returning placeholder');
    
    const fallbackSvg = `
      <svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
        <rect width="400" height="300" fill="#f3f4f6"/>
        <rect x="50" y="50" width="300" height="200" fill="#e5e7eb" stroke="#d1d5db" stroke-width="2"/>
        <text x="200" y="120" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" fill="#6b7280">PDF Preview</text>
        <text x="200" y="150" text-anchor="middle" font-family="Arial, sans-serif" font-size="12" fill="#9ca3af">Thumbnail not generated yet</text>
        <text x="200" y="170" text-anchor="middle" font-family="Arial, sans-serif" font-size="10" fill="#9ca3af">Run: scripts/process-thumbnails.mjs</text>
      </svg>
    `;
    
    return new NextResponse(fallbackSvg, {
      headers: {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
      },
    });

  } catch (error) {
    console.error('❌ Error getting thumbnail:', error);
    
    // Return fallback placeholder
    const fallbackSvg = `
      <svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
        <rect width="400" height="300" fill="#f3f4f6"/>
        <rect x="50" y="50" width="300" height="200" fill="#e5e7eb" stroke="#d1d5db" stroke-width="2"/>
        <text x="200" y="120" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" fill="#6b7280">PDF Preview</text>
        <text x="200" y="150" text-anchor="middle" font-family="Arial, sans-serif" font-size="12" fill="#9ca3af">Error loading thumbnail</text>
      </svg>
    `;
    
    return new NextResponse(fallbackSvg, {
      headers: {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'public, max-age=3600',
      },
    });
  }
}
