import { NextRequest, NextResponse } from 'next/server';
import { datalakeThumbnailService } from '@/lib/datalake-thumbnails';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ fileId: string; pageNumber: string }> }
) {
  try {
    const resolvedParams = await params;
    const { fileId } = resolvedParams;
    const pageNumber = resolvedParams.pageNumber;
    const { searchParams } = new URL(request.url);
    const size = (searchParams.get('size') || 'medium') as 'small' | 'medium' | 'large';
    const page = parseInt(pageNumber) || 1;
    
    console.log('🖼️ Page thumbnail request for fileId:', resolvedParams.fileId, 'page:', page, 'size:', size);

    // Validate fileId
    if (!resolvedParams.fileId) {
      return NextResponse.json(
        { error: 'File ID is required' },
        { status: 400 }
      );
    }

    // Validate page number
    if (page < 1 || page > 10) {
      return NextResponse.json(
        { error: 'Page number must be between 1 and 10' },
        { status: 400 }
      );
    }

    // Check if thumbnail already exists in Silver layer (with page-specific key)
    const pageSpecificFileId = `${resolvedParams.fileId}_page${page}`;
    try {
      const existingThumbnailUrl = await datalakeThumbnailService.getThumbnailUrl(pageSpecificFileId, size);
      if (existingThumbnailUrl) {
        console.log('✅ Page thumbnail found in Silver layer, redirecting to:', existingThumbnailUrl);
        return NextResponse.redirect(existingThumbnailUrl, {
          headers: {
            'Cache-Control': 'public, max-age=604800, immutable',
          },
        });
      }
    } catch (error) {
      console.log('📭 Page thumbnail not found in Silver layer');
    }

    // Thumbnail not found - return placeholder
    // Note: Page-specific thumbnails are generated by process-thumbnails.mjs script
    console.log('📭 Page-specific thumbnail not found, returning placeholder');
    
    const fallbackSvg = `
      <svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
        <rect width="400" height="300" fill="#f3f4f6"/>
        <rect x="50" y="50" width="300" height="200" fill="#e5e7eb" stroke="#d1d5db" stroke-width="2"/>
        <text x="200" y="120" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" fill="#6b7280">PDF Preview</text>
        <text x="200" y="150" text-anchor="middle" font-family="Arial, sans-serif" font-size="12" fill="#9ca3af">Page ${page}</text>
        <text x="200" y="170" text-anchor="middle" font-family="Arial, sans-serif" font-size="10" fill="#9ca3af">Thumbnail not generated yet</text>
      </svg>
    `;
    
    return new NextResponse(fallbackSvg, {
      headers: {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'public, max-age=3600',
      },
    });

  } catch (error) {
    console.error('❌ Error getting page thumbnail:', error);
    
    // Return fallback placeholder
    const fallbackSvg = `
      <svg width="400" height="300" xmlns="http://www.w3.org/2000/svg">
        <rect width="400" height="300" fill="#f3f4f6"/>
        <rect x="50" y="50" width="300" height="200" fill="#e5e7eb" stroke="#d1d5db" stroke-width="2"/>
        <text x="200" y="120" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" fill="#6b7280">PDF Preview</text>
        <text x="200" y="150" text-anchor="middle" font-family="Arial, sans-serif" font-size="12" fill="#9ca3af">Error loading thumbnail</text>
      </svg>
    `;
    
    return new NextResponse(fallbackSvg, {
      headers: {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'public, max-age=3600',
      },
    });
  }
}
